// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.9
// source: fraud/fraud.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Amount        int32                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentRequest) Reset() {
	*x = PaymentRequest{}
	mi := &file_fraud_fraud_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentRequest) ProtoMessage() {}

func (x *PaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fraud_fraud_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentRequest.ProtoReflect.Descriptor instead.
func (*PaymentRequest) Descriptor() ([]byte, []int) {
	return file_fraud_fraud_proto_rawDescGZIP(), []int{0}
}

func (x *PaymentRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PaymentRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PaymentRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *PaymentRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type FraudResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsFraud       bool                   `protobuf:"varint,1,opt,name=isFraud,proto3" json:"isFraud,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FraudResponse) Reset() {
	*x = FraudResponse{}
	mi := &file_fraud_fraud_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FraudResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FraudResponse) ProtoMessage() {}

func (x *FraudResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fraud_fraud_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FraudResponse.ProtoReflect.Descriptor instead.
func (*FraudResponse) Descriptor() ([]byte, []int) {
	return file_fraud_fraud_proto_rawDescGZIP(), []int{1}
}

func (x *FraudResponse) GetIsFraud() bool {
	if x != nil {
		return x.IsFraud
	}
	return false
}

func (x *FraudResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_fraud_fraud_proto protoreflect.FileDescriptor

const file_fraud_fraud_proto_rawDesc = "" +
	"\n" +
	"\x11fraud/fraud.proto\x12\x05fraud\"h\n" +
	"\x0ePaymentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x05R\x06userId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x05R\x06amount\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"C\n" +
	"\rFraudResponse\x12\x18\n" +
	"\aisFraud\x18\x01 \x01(\bR\aisFraud\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2I\n" +
	"\fFraudService\x129\n" +
	"\n" +
	"CheckFraud\x12\x15.fraud.PaymentRequest\x1a\x14.fraud.FraudResponseB\x13Z\x11fraud/proto;protob\x06proto3"

var (
	file_fraud_fraud_proto_rawDescOnce sync.Once
	file_fraud_fraud_proto_rawDescData []byte
)

func file_fraud_fraud_proto_rawDescGZIP() []byte {
	file_fraud_fraud_proto_rawDescOnce.Do(func() {
		file_fraud_fraud_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fraud_fraud_proto_rawDesc), len(file_fraud_fraud_proto_rawDesc)))
	})
	return file_fraud_fraud_proto_rawDescData
}

var file_fraud_fraud_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_fraud_fraud_proto_goTypes = []any{
	(*PaymentRequest)(nil), // 0: fraud.PaymentRequest
	(*FraudResponse)(nil),  // 1: fraud.FraudResponse
}
var file_fraud_fraud_proto_depIdxs = []int32{
	0, // 0: fraud.FraudService.CheckFraud:input_type -> fraud.PaymentRequest
	1, // 1: fraud.FraudService.CheckFraud:output_type -> fraud.FraudResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_fraud_fraud_proto_init() }
func file_fraud_fraud_proto_init() {
	if File_fraud_fraud_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fraud_fraud_proto_rawDesc), len(file_fraud_fraud_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fraud_fraud_proto_goTypes,
		DependencyIndexes: file_fraud_fraud_proto_depIdxs,
		MessageInfos:      file_fraud_fraud_proto_msgTypes,
	}.Build()
	File_fraud_fraud_proto = out.File
	file_fraud_fraud_proto_goTypes = nil
	file_fraud_fraud_proto_depIdxs = nil
}
